name: cv_website
description: A CV website built with Flutter Web
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  media_source: ^1.3.0
  url_launcher: ^6.2.2
  web: ^1.1.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
